apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-keys
  namespace: default
spec:
  encryptedData:
    APIKEY: AgAAxvIqIL6wWpZlb8W5aJRb94r9uMjKufeftk05ru/SIGRoeOpQNCQq1+7iiOEL8FMz7i68fUDTWmyhTpPhuUh7YpYAP+8+LfCok4OrCBVJK+Xjhei+X6jscLjhKCZafhoOKP1s+AcXIuA/2mQNTymWdK8q3yfDMJimE0yCwec4fo9DZ7dWElyVGtHGU739yGNaxnNUpbYxH+Vc9ECc2m0h+PGGWMbQrYLeg7PjD9qzsrYiCxUOimGs1p9SszCs44S+Mp7DwfKl2HzCSYsDHGwB/lF0B/LI1eI/P43W56D2U1Z7RzcgumhtmJ1SlPTOZwCoYO7/K5DnLB8kixWcbfskSVXNJuMaDsBwRmUXW7TY9xaE5ITypvYcMLdjXllatbcXURNYJN1DMo/Kp8Ms2FiEhBU3Aq/z1Wz0RsWrLjPbgI4CyeCoILzKd+QKBaXxaGbpse0OQZ4Y8SRfYGnB9hdB26n3pcKgVxrvLQHpfYrtdyO2afP7B0CXFxMQ1/+G/J9v7dZln+0A55dVNL3/NXAvWzFv5ct9w6lsWMSmRv2aavQs2VLWqGroCh+YeZraXDldydfuq441CGJ7oKlVn6fDo+DCgw76V81yDzZGu129R4IgC3wumM0dMlW5kzt4saPrE4tQy23mUoWA7KdjLE4xh1mztsDpvIrTFUFGNxxp+xgdOakpOLsoqzoNAeTmGp5mh4/l51t++l5KrJnnwCObuAns19M6oV9S+YUfFnA+IHEbUXwvpfp+Uq8sCjcXbkZf4w==
  template:
    metadata:
      creationTimestamp: null
      name: api-keys
      namespace: default
    type: Opaque

