apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-keys
  namespace: default
spec:
  encryptedData:
    APIKEY: AgBRf16jvGCKEzsFr0FCUam/TIdpdtVflbzqDW+uKbLOxCkGQStQi0jL+AxKJmaEBE/2mZaeziGx/8Ne49ej2vKJ9MsfYgHZ4QtZrvLZWyloq9IMWB0/YEnFp8JqEW4SouZv76iWmBslZAimCz8WvpOFyERUbXNvXneFfqqlwRsF+sCRy8/DltJyzOHZz1jvz7t3tGogc1NhEHKOVYE/RYDIhey48D2Bdz81E04zemQucFmPAIEanNLwDr0Uu1GFJYkHLTir0zBzBGUbUafuwhg9i8BTfKNIm1bBDA8ySkCm35RKWSPe6Zl9ATc/Nt8CHNoMv3nmnwDLNu9V9n0BhpwDriKECeKpJb9r/hm7wFLHirGr/thCflrp8c0ceWnEVe/oF2sApvYOaxr/W0rGEgj4qbYsGnUAu3gYYSlbNNWx0kmiPvM9oei6J3rMsjSTgudCPe3YyPcOhueWZ3CUgBN0heJc2fvCs3hnILjNkkBng1guap0/CNiKuWH5eYzjGBTr3xAzC94A5B2tgOCFWcogwZBTB9FrCNKLT/qiX7qC29WwbyYE0+mfbgc4bHM+hMR3zwyrH3LNBZK8Afk8zfAsOKrEalgicLEAQWeLKsgHGzYZhSlpdpYK4NRo9+p9ZH0C7Tw8rtX6YoLgnhcWN2FkT/wdqORUQTBOs0jFamsvzoKsDOiFr+3p7hM3ybTkHE4Ta8q3+MdLmE/h0LE85pbPlIV9gI8/fTxyLX4V8Y9C0o6tunlZpvFaol3DU/YDYWFE7g==
  template:
    metadata:
      creationTimestamp: null
      name: api-keys
      namespace: default
    type: Opaque

